/** Later visual stages of the buildings that grow with their level (AO-D087). Stage 1 is the plain `bld_*` icon in map.ts. */
import type { Grid } from '../render.js';

export const BUILDING_STAGE_ICONS = {
  bld_farm_2: [
    '................',
    '.......kk.......',
    '.....kkaakk.....',
    '....kahhhhak....',
    '...kaahhhhaak...',
    '...kAAAAAAAAk...',
    '...kwwwwwwwwk...',
    '...kwwkttkwwk...',
    '...kwwktTkwwk...',
    '..kkkkkttkkkkk..',
    '.kyjyjyjyjyjyk..',
    '.kuTuTuTuTuTuk..',
    '.kyjyjyjyjyjyk..',
    '.kuTuTuTuTuTuk..',
    '.kkkkkkkkkkkkk..',
    '................',
  ],
  bld_farm_3: [
    '................',
    '...kk.....kk....',
    '..kllk..kkaakk..',
    '.kllssk.kahhhak.',
    '.kllsSk.kAAAAAk.',
    '.klssSk.kwwwwwk.',
    '.klssSk.kwttTwk.',
    '.kssSSk.kwttTwk.',
    '.kkkkkkkkkkkkkk.',
    '.kyjyjyjyjyjyjk.',
    '.kuTuTuTuTuTuTk.',
    '.kyjyjyjyjyjyjk.',
    '.knNnNnNnNnNnNk.',
    '.kuTuTuTuTuTuTk.',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  bld_barracks_2: [
    '.......kkkk.....',
    '.......krrrk....',
    '.......krrk.....',
    '.......ktk......',
    '.......ktk......',
    '..kkaaaahhaaaak.',
    '.kaaAAAAAAAAaak.',
    '.kkkkkkkkkkkkkk.',
    '.kttuttttttuttk.',
    '.kttutkkkkttutk.',
    '.kttutkkkkttutk.',
    '.kttutkkkkttutk.',
    '.kttutkkkkttutk.',
    '.kTTTTTTTTTTTTk.',
    '..kkkkkkkkkkkk..',
    '................',
  ],
  bld_barracks_3: [
    '................',
    '................',
    '.k.k.k....k.k.k.',
    '.kkkkk....kkkkk.',
    '.klslk....klslk.',
    '.klslk.rr.klslk.',
    '.klslkkrrkklslk.',
    '.klslkllllklslk.',
    '.klsSklsslklsSk.',
    '.klsSklsslklsSk.',
    '.klsSkkTTkklsSk.',
    '.klsSkkTTkklsSk.',
    '.klsSkkTTkklsSk.',
    '.ksSSSkTTkSSSSk.',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  bld_mage_tower_2: [
    '......kiik......',
    '.....kiIIik.....',
    '......kiik......',
    '.......kk.......',
    '.....kkppkk.....',
    '....kppppppk....',
    '...kppppppppk...',
    '....klssssSk....',
    '....klsyysSk....',
    '....klssssSk....',
    '....klsyysSk....',
    '....klssssSk....',
    '....klssssSk....',
    '....klsTTsSk....',
    '....ksSTTSSk....',
    '.....kkkkkk.....',
  ],
  bld_mage_tower_3: [
    '.......kk.......',
    '......kIIk......',
    '......kiik......',
    '.....kkppkk.....',
    '.kk.kppppppk.kk.',
    'kppkkppppppkkppk',
    'klskklssssSkklsk',
    'klskklsyysSkklsk',
    'klskklssssSkklsk',
    'ksSkklsyysSkksSk',
    'ksSkklssssSkksSk',
    'klskklssssSkklsk',
    'klskklsTTsSkklsk',
    'klskklsTTsSkklsk',
    'ksSkksSTTSSkksSk',
    'kkkkkkkkkkkkkkkk',
  ],
} satisfies Record<string, Grid>;
