/** Unit role badges. The portraits are the 32x32 sprites in ../sprites (DL-10). */
import type { Grid } from '../render.js';

export const UNIT_ICON_GRIDS = {
  role_melee: [
    '..............k.',
    '.............kwk',
    '............kwww',
    '...........kwwsk',
    '..........kwwsk.',
    '.........kwwsk..',
    '...kk...kwwsk...',
    '..kyyk.kwwsk....',
    '..kyyykwwsk.....',
    '...kyyywsk......',
    '....kyyyk.......',
    '....kttyyk......',
    '...ktttyyyk.....',
    '.kktttkkyyk.....',
    'kytttk..kk......',
    'kyytk...........',
  ],
  role_ranged: [
    '....kk..........',
    '...kwtkk........',
    '...kwtttkk......',
    '...kwtttttk.....',
    '...kwkkttttk....',
    '...kwk.kkttk....',
    '...kwkk.kuttk.k.',
    '...kwrrkkkttkkgk',
    '...kwwwwwwwwwwww',
    '...kwrrkkkttkkgk',
    '...kwkk.ktttk.k.',
    '...kwk..kttk....',
    '...kwk.ktttk....',
    '...kwkkkttk.....',
    '...kwkttttk.....',
    '...kwttttk......',
  ],
  role_tank: [
    '...kkkkkkkkkk...',
    '..kllllllllllk..',
    '..klwsslSsswSk..',
    '..klssslSssSSk..',
    '..klssslSssSSk..',
    '..klssjjyysSSk..',
    '..klssyyyYsSSk..',
    '..klssyyyYsSSk..',
    '..klssYYYYsSSk..',
    '...klsslSsSSk...',
    '...kwsslSsSwk...',
    '....klslSSSk....',
    '....klslSSSk....',
    '.....kllSSk.....',
    '......kSSk......',
    '.......kk.......',
  ],
  role_caster: [
    '..........k...k.',
    '.........kwk.kwk',
    '..k.....kwwpk.k.',
    '.kwk...kwwwppk..',
    '..k....kpppppk..',
    '........kpppBk..',
    '.........kykk...',
    '........kyytk..k',
    '.......kuyytk.kw',
    '......kutttk...k',
    '.....kutttk.....',
    '....kutttk......',
    '...kutttk.......',
    '..kutttk........',
    '..ktttk.........',
    '..kttk..........',
  ],
  role_support: [
    '................',
    '.....kkkkkk.....',
    '.....kwwwgk.....',
    '.....kwwwgk.....',
    '.....kwwwgk.....',
    '.kkkkkwwwgkkkkk.',
    '.kwwwwwwwwwwwgk.',
    '.kwwwwwyywwwwgk.',
    '.kgggggyYgggggk.',
    '.kkkkkwwwgkkkkk.',
    '.....kwwwgk.....',
    '.....kwwwgk.....',
    '.....kwwwgk.....',
    '.....kggggk.....',
    '.....kkkkkk.....',
    '................',
  ],
  role_beast: [
    '................',
    '................',
    '.....kk..kk.....',
    '....kutkkutk....',
    '....kuTkkuTk....',
    '..kkktTkktTkkk..',
    '.kutkkk..kkkutk.',
    '.kuTkkkkkkkkuTk.',
    '.ktTkuuuuutktTk.',
    '..kkutttttttkk..',
    '...kuttttttTk...',
    '...kuttttttTk...',
    '...ktttttttTk...',
    '....ktTTTTTk....',
    '.....kkkkkk.....',
    '................',
  ],
} satisfies Record<string, Grid>;
